# Configure main menu and social menu
#[[main]]
#identifier = "portfolio"
#name = "Portfolio"
#url = "/"
#[main.params]
#icon = "article"
#newtab = false

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/mersad29"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "GitHub"
url = "https://www.linkedin.com/in/mersad29/"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "telegram"
name = "GitHub"
url = "https://t.me/m9rsad"

[social.params]
icon = "brand-telegram"